spring:
  application:
    name: cloud-consumer-feign-hystrix
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: true
hystrix:
    command:
        serverMethod:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000