server:
  port: 9411
spring:
  application:
    name: zipkin-server
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/