server:
  port: 8085
 
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
 
spring:
  application:
    name: cloud-zuul
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
 
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    user:
      path: /user/**
      serviceId: cloud-provider